In [8]:
# Puissance d’une matrice 2x2 
from math import* 
# Entrée des données 

a,b=eval(input("Coefficients de la 1ère ligne : ")) 
c,d=eval(input("Coefficients de la 2ème ligne : ")) 
n=eval(input("Valeur de l’exposant ?")) 
# Calculs et résultats 
A1,B1,C1,D1=1,0,0,1 
for i in range(0,n): 
    A2=A1*a+B1*c 
    B2=A1*b+B1*d 
    C2=C1*a+D1*c 
    D2=C1*b+D1*d 
    A1,B1,C1,D1=A2,B2,C2,D2 
M=[[A1,B1],[C1,D1]] 
print("Résultat du calcul :", M)

Coefficients de la 1ère ligne : 1,2
Coefficients de la 2ème ligne : 3,4
Valeur de l’exposant ?3
Résultat du calcul : [[37, 54], [81, 118]]


In [11]:
# Les points A, B et C sont-ils alignés ? 
from math import* 
xA,yA,zA=eval(input("Coordonnées du point A ? ")) 
xB,yB,zB=eval(input("Coordonnées du point B ? ")) 
xC,yC,zC=eval(input("coordonnées du point C ? ")) 
# Calculs et résultats 
a,b,c=xB-xA,yB-yA,zB-zA 
aa,bb,cc=xC-xA,yC-yA,zC-zA 
k1,k2,k3=a*bb-b*aa, b*cc-c*bb,a*cc-c*aa 
if k1==0 and k2==0 and k3==0: 
    print("Les points sont alignés.") 
else : 
    print("Les points ne sont pas alignés.")

Coordonnées du point A ? 0,0,0
Coordonnées du point B ? 1,1,1
coordonnées du point C ? 2,2,2
Les points sont alignés.


In [13]:
import numpy as np
from numpy.linalg import matrix_power
i = np.array([[0, 1], [-1, 0]]) # matrix equiv. of the imaginary unit
matrix_power(i, 3) # should = -i




array([[ 0, -1],
       [ 1,  0]])

In [14]:
matrix_power(i, 0)

array([[1, 0],
       [0, 1]])

In [15]:

matrix_power(i, -3) # should = 1/(-i) = i, but w/ f.p. elements


array([[ 0.,  1.],
       [-1.,  0.]])

In [16]:
q = np.zeros((4, 4))
q[0:2, 0:2] = -i
q[2:4, 2:4] = i
q # one of the three quaternion units not equal to 1

array([[ 0., -1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0., -1.,  0.]])

In [17]:
matrix_power(q, 2) # = -np.eye(4)

array([[-1.,  0.,  0.,  0.],
       [ 0., -1.,  0.,  0.],
       [ 0.,  0., -1.,  0.],
       [ 0.,  0.,  0., -1.]])

In [20]:
x = np.arange(9).reshape(3,3)
y = np.matrix(x)

a = y**3
b = np.linalg.matrix_power(x, 3)

print(a)
print(b)
#assert np.all(a==b)

[[ 180  234  288]
 [ 558  720  882]
 [ 936 1206 1476]]
[[ 180  234  288]
 [ 558  720  882]
 [ 936 1206 1476]]


In [21]:
y

matrix([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [22]:
a

matrix([[ 180,  234,  288],
        [ 558,  720,  882],
        [ 936, 1206, 1476]])

In [24]:
m = np.matrix([[2, -1, 0],
               [-1, 2, -1],
               [0, -1, 2]])

print(np.linalg.matrix_power(m, 0))
print(np.linalg.matrix_power(m, 1))
print(np.linalg.matrix_power(m, 2))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[ 2 -1  0]
 [-1  2 -1]
 [ 0 -1  2]]
[[ 5 -4  1]
 [-4  6 -4]
 [ 1 -4  5]]
